# Generated by Django 4.2.6 on 2023-10-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название отеля')),
                ('location', models.CharField(max_length=70, verbose_name='Расположение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/чел.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='hotels.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
