# Generated by Django 4.2.6 on 2023-10-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название отеля')),
                ('location', models.CharField(max_length=70, verbose_name='Расположение')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='Название номера')),
                ('slug', models.SlugField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/чел.')),
                ('descr', models.TextField(verbose_name='Описание комнаты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.category', verbose_name='Категория')),
                ('hotel_room', models.ForeignKey(default='hotel', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotels', verbose_name='Отель')),
            ],
        ),
    ]
