# Generated by Django 4.2.6 on 2023-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название отеля')),
                ('location', models.CharField(max_length=70, verbose_name='Расположение')),
                ('price', models.PositiveIntegerField(max_length=10, verbose_name='Цена/чел.')),
                ('existence', models.BooleanField(default=True, verbose_name='Наличие свободных мест')),
                ('booked', models.BooleanField(default=True, verbose_name='Бронирование')),
            ],
        ),
    ]
